# default config
baseurl = "https://blog.curso-r.com"
languageCode = "pt-br"
title = "Blog | Curso-R"
theme = "parsa-hugo"
summaryLength = "10"
paginate = 6
publishdir = "docs"

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# navigation
[[menu.main]]
name = "Home"
url = "#"
weight = 1
hasChildren = true

[[menu.main]]
name = "Cursos"
url = "https://www.curso-r.com/cursos"
weight = 2

[[menu.main]]
name = "Fórum"
url = "https://discourse.curso-r.com/"
weight = 3

# deult parameter
[params]
logo = "images/logo.png"
home = "Home"
# theme layout ( two layout is available, "1" and "2" )
layout = "1"
# Meta data
description = "Blog da Curso-R"
# Preloader
preloader = true
# search
search = true
# about author
author = "John Doe"
author_image = "images/banner-img.png"
bio = "I’m a Freelance Interactive Art Director based in France. Focusing across branding and identity, digital and print."
# Contact info
email = "contato@curso-r.com"
address = "[Acesse nosso fórum](https://discourse.curso-r.com/)"
# Contact Form Action
contact_form_action = "#"
# Google Analitycs
google_analitycs_id = "Your ID"
# copyright
copyright = "Copyright &copy; 2021 Curso-R"

# Instagram feed
[params.instafeed]
enable = true
access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"

# cookies
[params.cookies]
enable = false
expire_days = 2

# social site

[[params.social]]
icon = "ti-github"
url = "https://github.com/curso-r"


[[params.social]]
icon = "ti-twitter-alt"
url = "https://twitter.com/curso_r"

[[params.social]]
icon = "ti-instagram"
url = "https://www.instagram.com/cursoo_r/"

[[params.social]]
icon = "ti-linkedin"
url = "https://br.linkedin.com/company/curso-r"

[[params.social]]
icon = "ti-facebook"
url = "https://www.facebook.com/cursodeR/"

